# Generated by Django 4.1.7 on 2023-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career_choice',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
