# Generated by Django 4.1.7 on 2023-03-17 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_user_alter_coursecombinationjamb_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecombinationjamb',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jamb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecombinationwaec',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_waec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
